/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Entree;
import models.Produit;
import services.EntreeService;
import services.ProduitService;

/**
 *
 * @author IRWIN
 */
public class formEntree extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(formEntree.class.getName());

    /**
     * Creates new form formEntree
     */
    public formEntree() {
        initComponents();
        
        chargerProduits();
        generateNBE();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        qteEntree = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jDateEntree = new com.toedter.calendar.JDateChooser();
        jbtnValidEntr = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNBE = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProduits = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Nouvelle bon d'entrée");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Num Produit");

        jLabel3.setText("Quantité entrée");

        jLabel4.setText("Date entrée");

        jbtnValidEntr.setText("Validée");
        jbtnValidEntr.addActionListener(this::jbtnValidEntrActionPerformed);

        jLabel5.setText("Num Bon d'entrée");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jbtnValidEntr)
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(txtCode)
                    .addComponent(qteEntree)
                    .addComponent(jDateEntree, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(txtNBE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNBE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qteEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jbtnValidEntr)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableProduits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Code", "Désigantion", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableProduits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProduitsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProduits);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void chargerProduits(){
        ProduitService service =
            new ProduitService();
        
        Produit[] produits =
            service.getProduits();
        
        DefaultTableModel model =
            (DefaultTableModel)
                tableProduits.getModel();
        
        model.setRowCount(0);
        
        for (Produit p : produits) {
            model.addRow(new Object[]{
            p.getNumProduit(),
            p.getDesign(),
            p.getStock()
        });
        }
        
    }
    
    private void generateNBE() {

        EntreeService service = new EntreeService();

        // récupérer le dernier numéro (ex: BE01)
        String lastNBE = service.getLastNumeroBon();

        String newNBE;

        if (lastNBE == null || lastNBE.isEmpty()) {
            newNBE = "BE01";
        } else {

            // enlever "BE"
            String numberPart = lastNBE.substring(2);

            // convertir en entier
            int num = Integer.parseInt(numberPart);

            // incrémenter
            num++;

            // formater avec 2 chiffres
            newNBE = String.format("BE%02d", num);
        }

        // afficher dans ton champ texte
        txtNBE.setText(newNBE);
    }
    
    
    
    private void tableProduitsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProduitsMouseClicked
        // TODO add your handling code here:
        int ligne = tableProduits.getSelectedRow();

        if (ligne >= 0) {

            txtCode.setText(tableProduits.getValueAt(ligne, 0).toString());
            
        }
    }//GEN-LAST:event_tableProduitsMouseClicked

    private void jbtnValidEntrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnValidEntrActionPerformed
        // TODO add your handling code here:
        Date dateEntree = jDateEntree.getDate();
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        String date_sdf = sdf.format(dateEntree);
        
        
        Entree entree = new Entree(
                txtNBE.getText(),
                txtCode.getText(),
                Integer.parseInt(qteEntree.getText()),
                date_sdf
        );
        
        EntreeService service = new EntreeService();
        
        service.ajouterEntree(entree);
        
        chargerProduits();
        
        JOptionPane.showMessageDialog(
            this,
            "Bon d'entrée ajouter avec succès !",
            "Succès",
            JOptionPane.INFORMATION_MESSAGE
        );
        
        generateNBE();
        txtCode.setText("");
        qteEntree.setText("");
        jDateEntree.setDate(null);
        
    }//GEN-LAST:event_jbtnValidEntrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new formEntree().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateEntree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnValidEntr;
    private javax.swing.JTextField qteEntree;
    private javax.swing.JTable tableProduits;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtNBE;
    // End of variables declaration//GEN-END:variables
}
