/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Produit;
import models.Sortie;
import services.ProduitService;
import services.SortieService;

/**
 *
 * @author IRWIN
 */
public class formSortie extends javax.swing.JFrame {

    /**
     * Creates new form formSotie
     */
    public formSortie() {
        initComponents();
        
        chargerProduits();
        generateNBS();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        qteSortie = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jDateSortie = new com.toedter.calendar.JDateChooser();
        jbtnValidEntr = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNBS = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProduits = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Nouvelle bon de sortie");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Num Produit");

        jLabel3.setText("Quantité sortie");

        jLabel4.setText("Date sortie");

        jbtnValidEntr.setText("Validée");
        jbtnValidEntr.addActionListener(this::jbtnValidEntrActionPerformed);

        jLabel5.setText("Num Bon de sortie");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jbtnValidEntr)
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(txtCode)
                    .addComponent(qteSortie)
                    .addComponent(jDateSortie, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(txtNBS))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qteSortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateSortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jbtnValidEntr)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        tableProduits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Code", "Désigantion", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableProduits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProduitsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProduits);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(17, 17, 17)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    private void chargerProduits(){
        ProduitService service =
            new ProduitService();
        
        Produit[] produits =
            service.getProduits();
        
        DefaultTableModel model =
            (DefaultTableModel)
                tableProduits.getModel();
        
        model.setRowCount(0);
        
        for (Produit p : produits) {
            model.addRow(new Object[]{
            p.getNumProduit(),
            p.getDesign(),
            p.getStock()
        });
        }
        
    }
    
    private void generateNBS() {

        SortieService service = new SortieService();

        // récupérer le dernier numéro (ex: BE01)
        String lastNBS = service.getLastNumeroBon();

        String newNBS;

        if (lastNBS == null || lastNBS.isEmpty()) {
            newNBS = "BS01";
        } else {

            // enlever "BE"
            String numberPart = lastNBS.substring(2);

            // convertir en entier
            int num = Integer.parseInt(numberPart);

            // incrémenter
            num++;

            // formater avec 2 chiffres
            newNBS = String.format("BS%02d", num);
        }

        // afficher dans ton champ texte
        txtNBS.setText(newNBS);
    }
    
    private void jbtnValidEntrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnValidEntrActionPerformed
        // TODO add your handling code here:
        Date dateSortie = jDateSortie.getDate();

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        String date_sdf = sdf.format(dateSortie);

        Sortie sortie = new Sortie(
            txtNBS.getText(),
            txtCode.getText(),
            Integer.parseInt(qteSortie.getText()),
            date_sdf
        );

        SortieService service = new SortieService();

        service.ajouterSortie(sortie);

        chargerProduits();

        JOptionPane.showMessageDialog(
            this,
            "Bon de sortie ajouter avec succès !",
            "Succès",
            JOptionPane.INFORMATION_MESSAGE
        );

        generateNBS();
        txtCode.setText("");
        qteSortie.setText("");
        jDateSortie.setDate(null);

    }//GEN-LAST:event_jbtnValidEntrActionPerformed

    private void tableProduitsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProduitsMouseClicked
        // TODO add your handling code here:
        int ligne = tableProduits.getSelectedRow();

        if (ligne >= 0) {

            txtCode.setText(tableProduits.getValueAt(ligne, 0).toString());

        }
    }//GEN-LAST:event_tableProduitsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateSortie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnValidEntr;
    private javax.swing.JTextField qteSortie;
    private javax.swing.JTable tableProduits;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtNBS;
    // End of variables declaration//GEN-END:variables
}
