/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Entree;
import models.Produit;
import models.Sortie;
import services.EntreeService;
import services.ProduitService;
import services.SortieService;
import utils.ApiClient;

/**
 *
 * @author IRWIN
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private Produit[] produitsCombo;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        tryConnect();
        chargerBon();
        chargerProduitsCombo();
        
        btnMod.setEnabled(false);
        btnSup.setEnabled(false);
        txtNumBon.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jpMain = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jpProduits = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProduits = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        txtCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDesignation = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jButtonModifier = new javax.swing.JButton();
        jButtonAjouter = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        searchProd = new javax.swing.JTextField();
        btnSearch = new javax.swing.JLabel();
        jpMov = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBon = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtNumBon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtQte = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnMod = new javax.swing.JButton();
        btnSup = new javax.swing.JButton();
        txtDate = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        txtProduit = new javax.swing.JTextField();
        selecteProd = new javax.swing.JComboBox<>();
        jpEtatStock = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableEtatStock = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Gestion de Stock");
        jLabel1.setToolTipText("");
        jLabel1.setDoubleBuffered(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(622, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 70));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Entrées");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Produits");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Sorties");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Etat Stock");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("Mouvements");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(345, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 600));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jpMain.setPreferredSize(new java.awt.Dimension(809, 594));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Bienvenue ");

        javax.swing.GroupLayout jpMainLayout = new javax.swing.GroupLayout(jpMain);
        jpMain.setLayout(jpMainLayout);
        jpMainLayout.setHorizontalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMainLayout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(jLabel8)
                .addContainerGap(370, Short.MAX_VALUE))
        );
        jpMainLayout.setVerticalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMainLayout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jLabel8)
                .addContainerGap(302, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Produits");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        tableProduits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Code", "Désigantion", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableProduits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProduitsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProduits);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        txtCode.setText("txtCode");

        jLabel3.setText("Code :");

        jLabel4.setText("Désignation :");

        txtDesignation.setText("txtDesignation");

        jLabel5.setText(" Stock : ");

        txtStock.setText("txtStock");

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(this::jButtonModifierActionPerformed);

        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(this::jButtonAjouterActionPerformed);

        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(this::btnSupprimerActionPerformed);

        jButton7.setText("Actualiser");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jButtonModifier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAjouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButtonAjouter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonModifier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnSupprimer)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(txtCode)
                    .addComponent(txtDesignation)
                    .addComponent(txtStock)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-search-16.png"))); // NOI18N
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });

        jButtonModifier.setEnabled(false);
        btnSupprimer.setEnabled(false);

        javax.swing.GroupLayout jpProduitsLayout = new javax.swing.GroupLayout(jpProduits);
        jpProduits.setLayout(jpProduitsLayout);
        jpProduitsLayout.setHorizontalGroup(
            jpProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProduitsLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jpProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpProduitsLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpProduitsLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchProd, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        jpProduitsLayout.setVerticalGroup(
            jpProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProduitsLayout.createSequentialGroup()
                .addGroup(jpProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpProduitsLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpProduitsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)))
                .addGroup(jpProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpMov.setPreferredSize(new java.awt.Dimension(809, 594));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Mouvement de stock");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        tableBon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Num Bon", "Produits", "Quantité", "Date", "Type"
            }
        ));
        tableBon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableBon);

        jLabel9.setText("Nun Bon");

        jLabel10.setText("Quantité");

        jLabel11.setText("Date");

        btnMod.setText("Modifié");
        btnMod.addActionListener(this::btnModActionPerformed);

        btnSup.setText("Supprimer");

        jLabel12.setText("Produit");

        selecteProd.addActionListener(this::selecteProdActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumBon, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(txtQte)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtProduit))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecteProd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSup)
                .addGap(98, 98, 98))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(selecteProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtNumBon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(5, 5, 5)
                        .addComponent(txtProduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMod)
                    .addComponent(btnSup))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpMovLayout = new javax.swing.GroupLayout(jpMov);
        jpMov.setLayout(jpMovLayout);
        jpMovLayout.setHorizontalGroup(
            jpMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMovLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpMovLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpMovLayout.setVerticalGroup(
            jpMovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMovLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpEtatStock.setPreferredSize(new java.awt.Dimension(809, 594));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Etat Stock");

        tableEtatStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Désignstion", "stock"
            }
        ));
        jScrollPane3.setViewportView(tableEtatStock);

        javax.swing.GroupLayout jpEtatStockLayout = new javax.swing.GroupLayout(jpEtatStock);
        jpEtatStock.setLayout(jpEtatStockLayout);
        jpEtatStockLayout.setHorizontalGroup(
            jpEtatStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEtatStockLayout.createSequentialGroup()
                .addGroup(jpEtatStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEtatStockLayout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(jLabel7))
                    .addGroup(jpEtatStockLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jpEtatStockLayout.setVerticalGroup(
            jpEtatStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEtatStockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jpProduits.setVisible(false);
        jpEtatStock.setVisible(false);
        jpMov.setVisible(false);
        jpMain.setVisible(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpProduits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(32, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpEtatStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jpProduits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpMov, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpEtatStock, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addGap(82, 82, 82)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jpMain, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addGap(72, 72, 72)))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 820, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void tryConnect() {
        String result = ApiClient.get("/produits");

        if (result == null) {
            JOptionPane.showMessageDialog(
                this,
                "Erreur de connexion au serveur",
                "Erreur",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }
    private void chargerProduits(){
        chargerProduits(null);
    }

    private void chargerProduits(String recherche) {
        ProduitService service =
            new ProduitService();
        
        Produit[] produits =
            service.getProduits();
        
        DefaultTableModel model =
            (DefaultTableModel)
                tableProduits.getModel();
        
        model.setRowCount(0);

        if (produits != null) {
            for (Produit p : produits) {
                if (recherche != null && !recherche.isEmpty()) {
                    String terme = recherche.toLowerCase();
                    boolean matchCode = p.getNumProduit() != null && p.getNumProduit().toLowerCase().contains(terme);
                    boolean matchDesign = p.getDesign() != null && p.getDesign().toLowerCase().contains(terme);
                    if (!matchCode && !matchDesign) {
                        continue;
                    }
                }

                model.addRow(new Object[]{
                    p.getNumProduit(),
                    p.getDesign(),
                    p.getStock()
                });
            }
        }
        
        txtCode.setText("");
        txtDesignation.setText("");
        txtStock.setText("");
    }

    private void chargerBon() {

        EntreeService entreeService = new EntreeService();
        SortieService sortieService = new SortieService();

        Entree[] entrees = entreeService.getEntrees();
        Sortie[] sorties = sortieService.getSorties();

        String filtreProduit = null;
        String selectedProduct = (String) selecteProd.getSelectedItem();

        if (selectedProduct != null && !"Tous les produits".equals(selectedProduct)) {
            if (produitsCombo != null) {
                for (Produit p : produitsCombo) {
                    if (selectedProduct.equals(p.getDesign())) {
                        filtreProduit = p.getNumProduit();
                        break;
                    }
                }
            }
        }

        DefaultTableModel modelBon = (DefaultTableModel) tableBon.getModel();
        modelBon.setRowCount(0);

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        // 🔵 Entrées
        for (Entree e : entrees) {
            if (filtreProduit != null && !filtreProduit.equals(e.getNumProduit())) {
                continue;
            }

            String dateFormattee = e.getDateEntree();

            try {
                dateFormattee = sdf.format(sdf.parse(e.getDateEntree()));
            } catch (Exception ex) {
                dateFormattee = e.getDateEntree(); // fallback
            }

            modelBon.addRow(new Object[]{
                e.getNumBonEntree(),
                e.getNumProduit(),
                e.getQteEntree(),
                dateFormattee,
                "Entrée"
            });
        }

        // 🔴 Sorties
        for (Sortie s : sorties) {
            if (filtreProduit != null && !filtreProduit.equals(s.getNumProduit())) {
                continue;
            }

            String dateFormattee = s.getDateSortie();

            try {
                dateFormattee = sdf.format(sdf.parse(s.getDateSortie()));
            } catch (Exception ex) {
                dateFormattee = s.getDateSortie();
            }

            modelBon.addRow(new Object[]{
                s.getNumBonSortie(),
                s.getNumProduit(),
                s.getQteSortie(),
                dateFormattee,
                "Sortie"
            });
        }

        txtNumBon.setText("");
        txtDate.setDate(null);
    }
    
    private void chargerProduitsCombo() {

        ProduitService service = new ProduitService();

        Produit[] produits = service.getProduits();
        produitsCombo = produits;

        selecteProd.removeAllItems();
        selecteProd.addItem("Tous les produits");

        for (Produit p : produits) {
            selecteProd.addItem(p.getDesign());
        }
    }
    
    private void chargerEtatStock(){
        ProduitService produitService = new ProduitService();
        EntreeService entreeService = new EntreeService();
        SortieService sortieService = new SortieService();

        Produit[] produits = produitService.getProduits();
        Entree[] entrees = entreeService.getEntrees();
        Sortie[] sorties = sortieService.getSorties();

        if (produits == null) {
            produits = new Produit[0];
        }
        if (entrees == null) {
            entrees = new Entree[0];
        }
        if (sorties == null) {
            sorties = new Sortie[0];
        }

        DefaultTableModel model = (DefaultTableModel) tableEtatStock.getModel();
        model.setRowCount(0);

        for (Produit p : produits) {
            int totalEntree = 0;
            int totalSortie = 0;
            String codeProduit = p.getNumProduit();

            for (Entree e : entrees) {
                if (codeProduit.equals(e.getNumProduit())) {
                    totalEntree += e.getQteEntree();
                }
            }

            for (Sortie s : sorties) {
                if (codeProduit.equals(s.getNumProduit())) {
                    totalSortie += s.getQteSortie();
                }
            }

            int stockCalcule = p.getStock() + totalEntree - totalSortie;
            model.addRow(new Object[]{
                p.getDesign(),
                stockCalcule
            });
        }
    }

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        formEntree formulaire = new formEntree();
        formulaire.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jpProduits.setVisible(true);
        chargerProduits();
        jpEtatStock.setVisible(false);
        jpMov.setVisible(false);
        jpMain.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
       Produit produit = new Produit(
                txtCode.getText(),
                txtDesignation.getText(),
                Integer.parseInt(
                        txtStock.getText()
                )
        );
        
        ProduitService service = new ProduitService();
        
        service.ajouterProduit(produit);
        
        chargerProduits();
        
        JOptionPane.showMessageDialog(
            this,
            "Ajout effectué avec succès !",
            "Succès",
            JOptionPane.INFORMATION_MESSAGE
        );      
      
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        // TODO add your handling code here:
        int ligne = tableProduits.getSelectedRow();
        
        if (ligne >= 0) {

            int choix = JOptionPane.showConfirmDialog(
                    this,
                    "Voulez-vous vraiment supprimer ce produit ?",
                    "Confirmation de suppression",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );

            if (choix == JOptionPane.YES_OPTION) {

                String code = tableProduits.getValueAt(ligne, 0).toString();

                ProduitService service = new ProduitService();
                service.supprimerProduit(code);

                chargerProduits();

                JOptionPane.showMessageDialog(
                        this,
                        "Produit supprimé avec succès !",
                        "Succès",
                        JOptionPane.INFORMATION_MESSAGE
                );
            }

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Veuillez sélectionner un produit à supprimer.",
                    "Aucune sélection",
                    JOptionPane.WARNING_MESSAGE
            );
        }
        btnSupprimer.setEnabled(false);
        jButtonModifier.setEnabled(false);
        jButtonAjouter.setEnabled(true);
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
       chargerProduits();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jpProduits.setVisible(false);
        jpEtatStock.setVisible(true);
        jpMov.setVisible(false);
        jpMain.setVisible(false);
        
        chargerEtatStock();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jpProduits.setVisible(false);
        jpEtatStock.setVisible(false);
        jpMov.setVisible(true);
        jpMain.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        // TODO add your handling code here:
        int ligne = tableProduits.getSelectedRow();
        
        if (ligne >= 0) {
            Produit produit = new Produit(
                txtCode.getText(),
                txtDesignation.getText(),
                Integer.parseInt(
                        txtStock.getText()
                )
            );
        
            
            
            int choix = JOptionPane.showConfirmDialog(
                    this,
                    "Voulez-vous vraiment modifier ce produit ?",
                    "Confirmation de la modidfication",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );
            
            if (choix == JOptionPane.YES_OPTION) {
                ProduitService service = new ProduitService();
                service.modifierProduit(produit);
                chargerProduits();
                
                JOptionPane.showMessageDialog(
                        this,
                        "Produit modifié avec succès !",
                        "Succès",
                        JOptionPane.INFORMATION_MESSAGE
                );
            }
            
        }
        btnSupprimer.setEnabled(false);
        jButtonModifier.setEnabled(false);
        jButtonAjouter.setEnabled(true);
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void tableProduitsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProduitsMouseClicked
        // TODO add your handling code here:
        int ligne = tableProduits.getSelectedRow();

        if (ligne >= 0) {

            txtCode.setText(tableProduits.getValueAt(ligne, 0).toString());
            txtDesignation.setText(tableProduits.getValueAt(ligne, 1).toString());
            txtStock.setText(tableProduits.getValueAt(ligne, 2).toString());
            
            btnSupprimer.setEnabled(true);
            jButtonModifier.setEnabled(true);
            jButtonAjouter.setEnabled(false);
        }
    }//GEN-LAST:event_tableProduitsMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        formSortie formulaire = new formSortie();
        formulaire.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tableBonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBonMouseClicked
        // TODO add your handling code here:
        int ligne = tableBon.getSelectedRow();

        if (ligne >= 0) {
            

            txtNumBon.setText(tableBon.getValueAt(ligne, 0).toString());
            txtProduit.setText(tableBon.getValueAt(ligne, 1).toString());
            txtQte.setText(tableBon.getValueAt(ligne, 2).toString());
            txtDate.setDate(java.sql.Date.valueOf(tableBon.getValueAt(ligne, 3).toString()));
        }
        btnMod.setEnabled(true);
        btnSup.setEnabled(true);
        
    }//GEN-LAST:event_tableBonMouseClicked

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        // TODO add your handling code here:
        int ligne = tableBon.getSelectedRow();

        if (ligne >= 0) {

            String numBon = txtNumBon.getText();
            int qte = Integer.parseInt(txtQte.getText());
            
            Date date = txtDate.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date_sdf = sdf.format(date);
            
            String type = tableBon.getValueAt(ligne, 4).toString();
            String NumProduit = tableBon.getValueAt(ligne, 1).toString();

            int choix = JOptionPane.showConfirmDialog(
                    this,
                    "Voulez-vous vraiment modifier ce bon ?: "+ NumProduit + " " + numBon + " " + qte + " " + date_sdf,
                    "Confirmation de la modidfication",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );

            if (choix == JOptionPane.YES_OPTION) {
                if (type.equals("Entrée")) {
                    EntreeService service = new EntreeService();
                    Entree entree = new Entree( numBon, NumProduit,  qte, date_sdf);
                    service.modifierEntree(entree);
                } else {
                    SortieService service = new SortieService();
                    Sortie sortie = new Sortie( numBon, NumProduit,  qte, date_sdf);
                    service.modifierSortie(sortie);
                }
                chargerBon();

                JOptionPane.showMessageDialog(
                        this,
                        "Bon modifié avec succès !",
                        "Succès",
                        JOptionPane.INFORMATION_MESSAGE
                );
            }
        }
         
    }//GEN-LAST:event_btnModActionPerformed

    private void selecteProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecteProdActionPerformed
        // TODO add your handling code here:
        chargerBon();
    }//GEN-LAST:event_selecteProdActionPerformed

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        String recherche = searchProd.getText();
        chargerProduits(recherche);
    }//GEN-LAST:event_btnSearchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMod;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JButton btnSup;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jpEtatStock;
    private javax.swing.JPanel jpMain;
    private javax.swing.JPanel jpMov;
    private javax.swing.JPanel jpProduits;
    private javax.swing.JTextField searchProd;
    private javax.swing.JComboBox<String> selecteProd;
    private javax.swing.JTable tableBon;
    private javax.swing.JTable tableEtatStock;
    private javax.swing.JTable tableProduits;
    private javax.swing.JTextField txtCode;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtDesignation;
    private javax.swing.JTextField txtNumBon;
    private javax.swing.JTextField txtProduit;
    private javax.swing.JTextField txtQte;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
